### PR TITLE
Set up directory structure

### PR DESCRIPTION
**Pull request by dinobenj**
Created Directory Structure. Let me know if this looks good to you. If you have any comments or changes, you can request changes in this PR. The main design of this is for each person to make a component directory. These components can be compiled separately, or together with code present in the runner file which we will use as a way to run every component at the same time when we compile. This prevents merge conflicts and allows us to test components by themselves. Again, we are gonna be using the branch paradigm when changes are being made. All PR's need a reviewer to be merged into main or dev. Preferably we will use dev but Im lazy sometimes so while we should use best practice, its ok to just push to main if we need a patch fix. For people dealing with DLL's or large log files, I gotta think of a setup for that but I would ask that you dont push them into the repo bc it makes cloning/pulling it more annoying. To prevent this, edit the .gitignore to not add any large files you generate. LMK if you guys have any comments or concerns.

├── LICENSE
├── README.md
├── components
│   ├── memchecker
│   │   └── src
│   └── runner.cpp
├── db
│   └── scripts
│       └── template.sql
└── src
    └── main.cpp

### CODE REVIEW

**Review by Busaba-Nicholas — APPROVED** [review]
LGTM!

**Review by CamoGuy3000 — APPROVED** [review]
Looks good, excited to start :)

**Review by yuguangl — APPROVED** [review]
all g

**Review by adamsmart830 — APPROVED** [review]
Very nice 😎

**Pull request merged**
